name: "Github action to deploy files to s3 bucket"
description: "Easy way to build and upload distributable files of Vue application to amazon s3 bucket"

branding:
  icon: "archive"
  color: "orange"

inputs:
  AWS_ACCESS_KEY_ID:
    description: "Amazon access key id"
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: "Amazon secret access key"
    required: true
  AWS_DEFAULT_REGION:
    description: "Bucket region. (Ex: us-east-1)"
    required: true
  AWS_BUCKET_NAME:
    description: "Aws bucket name"
    required: true
  BUCKET_PATH:
    description: "Additional path where the files will be uploaded '/pr/84'"
    required: false
    default: ''
  DIST_LOCATION_CODE:
    description: "Location of the dist files. Default: dist."
    required: false
    default: ./dist
  OVERWIRTE_CONTENT:
    description: "Overwrite the previous deployment. Default: false"
    required: false
    default: "false"

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
    AWS_DEFAULT_REGION: ${{ inputs.AWS_DEFAULT_REGION }}
    AWS_BUCKET_NAME: ${{ inputs.AWS_BUCKET_NAME }}
    BUCKET_PATH: ${{ inputs.BUCKET_PATH }}
    DIST_LOCATION_CODE: ${{ inputs.DIST_LOCATION_CODE }}
    OVERWIRTE_CONTENT: ${{ inputs.OVERWIRTE_CONTENT }}
